### ISSUE TITLE
Invalid HTML

### ISSUE THREAD

**Issue by csswizardry** [analogue-andy/analogue-andy.github.io#2]
[This is invalid HTML](https://github.com/andycochrane/andycochrane.github.io/blob/3d77df42fb97e9365c469cea921ab7afbdb210e9/index.html#L423-L427), and we shouldn’t be using content for stylistic purposes. Switch out for a CSS solution 👍

**Comment by andycochrane** [comment]
Daft mistake. Thanks for the heads up. See Pull Request #3

**Comment by csswizardry** [comment]
Nice quick fix! Closing this 👍
